management:
  endpoints:
    web:
    exposure:
      include: health,info,env,metrics
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

### 自定义 actuator 的 info endpoint 的信息
info:
  app:
    desc: "customize info endpoint"
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
