-- 来源于自动生成的建表脚本

drop table department if exists;

drop table employee if exists;

create table department (
   id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table employee (
   id bigint generated by default as identity,
    age integer not null,
    email varchar(255),
    name varchar(255),
    dept_id bigint not null,
    primary key (id)
);

alter table employee
   add constraint FKaqchbcb8i6nvtl9g6c72yba0p
   foreign key (dept_id)
   references department;
