-- 来源于自动生成的建表脚本
    drop table person if exists;
    
    create table person (
       id bigint generated by default as identity,
        first_name varchar(255),
        last_name varchar(255),
        primary key (id)
    );
	
	